# action.yml
name: 'Get Package Version'
author: S2
description: 'get your package.json infos'
inputs:
  path:
    description: 'package.json address'
outputs:
  <key>: # this from inputs key
    description: 'your package.json info'
branding:
  icon: arrow-down
  color: white
runs:
  using: 'node12'
  main: 'dist/index.js'
